# $Id: cs_ajoin.2.sql 33 2010-05-10 02:46:01Z openglx $

ALTER TABLE cs_ajoin
  ADD COLUMN order_id INT(2) NOT NULL default '0' AFTER scid,
  ADD INDEX(scid),
  ADD CONSTRAINT FK_CSA1 FOREIGN KEY (snid) REFERENCES nickserv (snid)
    ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT FK_CSA2 FOREIGN KEY (scid) REFERENCES chanserv (scid)
    ON DELETE CASCADE ON UPDATE CASCADE;
