void m_sjoin(int parc,char *parv[]);
void m_part(int parc,char *parv[]);
void m_kick(int parc,char *parv[]);
void m_topic(int parc,char *parv[]);
void m_pong(int parc,char *parv[]);
void m_ping(int parc,char *parv[]);
void m_mode(int parc,char *parv[]);
void m_privmsg(int parc,char *parv[]);
void m_server(int parc,char *parv[]);
void m_squit(int parc,char *parv[]);
void m_nick(int parc,char *parv[]);
void m_quit(int parc,char *parv[]);
void m_kill(int parc,char *parv[]);
/* ifdef IRCD_PLEXUS */
void m_uid(int parc,char *parv[]);
void m_pass(int parc,char *parv[]);
void m_tmode(int parc,char *parv[]);
void m_join(int parc,char *parv[]);
void m_sid(int parc,char *parv[]);
